/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.vrsoftware.gui;

import com.example.vrsoftware.gui.view.TelaPrincipal;

public class App {
 
    public static void main(String[] args) {
        // Cria e exibe a TelaPrincipal
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }
}
